export const ADD_CHECKBOX_VALUE = 'ADD_CHECKBOX_VALUE';
export const UPDATE_CHECKBOX_VALUE = 'UPDATE_CHECKBOX_VALUE';
export const UPDATE_HEADER_CHECKBOX_VALUE = 'UPDATE_HEADER_CHECKBOX_VALUE';
export const DELETE_CHECKBOX_VALUE = 'DELETE_CHECKBOX_VALUE';